# Global params
# config/_default/languages.en.toml

colorScheme = "github"
defaultAppearance = "dark"
autoSwitchAppearance = true
paginate = 8

enableSearch = false
enableCodeCopy = true
enableStructuredBreadcrumbs = false

mainSections = ["posts", "projects"]
disableImageZoom = false
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

# logo = "logos/primary-logos.png"
# secondaryLogo =  "logos/secondary-logos.png"

[header]
  layout = "fixed-fill"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page"
  homepageImage = "img/home-img.webp"
  showRecent = true
  showRecentItems = 8
  showMoreLink = true
  showMoreLinkDest = "/categories/posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = true
  showAuthor = false
  showHero = true
  heroStyle =  "background"
  layoutBackgroundBlur = false
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editURL = ""
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showWordCount = false
  showRelatedContent = false
  relatedContentLimit = 3
  showTaxonomies = true
  # sharingLinks

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = false # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = false
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[term]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false